---
- hosts: all
  become: yes
  tasks:
  - name: Set up osquery keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
  - name: Set up osquery repository
    apt_repository:
      repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
      state: present
  - name: Install osquery
    apt:
      name: osquery
      update_cache: yes
  - name: Copy flagfile for osquery service config
    copy:
      src: configuration/osquery.flags
      dest: /etc/osquery/osquery.flags
      owner: root
      group: root
      mode: 0644
  - name: Copy conf for osquery service config
    copy:
      src: configuration/osquery.conf
      dest: /etc/osquery/osquery.conf
      owner: root
      group: root
      mode: 0644
  - name: Enable osqueryd to start on boot
    systemd:
      name: osqueryd
      state: started
      enabled: yes
      daemon_reload: yes
  - name: Delete osquery RocksDB
    file:
      path: /var/osquery/osquery.db
      state: absent
  - name: Restart osqueryd
    service:
      name: osqueryd
      state: restarted
